version: '3.4'

services:

  ms-sql-2:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55W0rd"
    ports:
      - "1453:1433"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build: 
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    environment:
      DefaultHost: 'ms-sql-2'
    ports:
     - "8080:80"
    depends_on:
     - ms-sql-2

  
  